change technique

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,21 +32,30 @@ jobs:
       - name: Test build environment
         run: devenv test
 
-      # Start PostgreSQL from devenv
-      - name: Start PostgreSQL from devenv
+      # Start PostgreSQL from devenv and ensure it's ready
+      - name: Start PostgreSQL and wait until ready
         run: |
-          devenv up &
+          start-postgres &
           echo "Waiting for PostgreSQL to be ready..."
-          timeout=60
+
+          timeout=120
           start_time=$(date +%s)
-          while ! nc -z localhost 5432; do
+          while ! devenv run check-postgres &>/dev/null; do
             current_time=$(date +%s)
             elapsed_time=$((current_time - start_time))
             if [ $elapsed_time -ge $timeout ]; then
               echo "Timed out waiting for PostgreSQL after ${timeout} seconds."
-              exit 1
+              devenv run start-postgres
+              sleep 5
+              if ! devenv run check-postgres; then
+                echo "Failed to start PostgreSQL after retry."
+                exit 1
+              else
+                echo "PostgreSQL successfully started after retry."
+                break
+              fi
             fi
-            sleep 1
+            sleep 2
           done
           echo "PostgreSQL is ready."
 
